columnSuffix: null
handle: newTab
instructions: null
name: 'New Tab'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
