dateModified: 1720995876
email:
  fromEmail: syed.ext@gmail.com
  fromName: sai-yed.com
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    80485932-678f-4c77-85dc-84337e9fa906: sai-yed.com # sai-yed.com
    f14dfdae-aa49-43fc-af38-923d87b42db3: sai-yed.com # sai-yed.com
system:
  edition: solo
  live: true
  name: sai-yed.com
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
